apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-service
  namespace: wallet
  labels:
    app.kubernetes.io/name: wallet-service
    app.kubernetes.io/part-of: core-wallet
  annotations:
    # AWS EKS: IAM Role for Service Account (IRSA)
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/core-wallet-service
    {}
