package http

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"regexp"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
	"github.com/go-playground/validator/v10"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin"

	_ "github.com/ewallet-pg/wallet-service/docs" // generated OpenAPI spec (make swagger)
	"github.com/ewallet-pg/wallet-service/internal/config"
	"github.com/ewallet-pg/wallet-service/internal/http/handler"
	"github.com/ewallet-pg/wallet-service/internal/http/middleware"
	"github.com/ewallet-pg/wallet-service/internal/usecase"
)

// Server wraps a configured *http.Server with graceful shutdown.
type Server struct {
	cfg    config.HTTP
	server *http.Server
	log    *slog.Logger
}

// New builds the gin engine + applies middleware + mounts routes.
func New(cfg config.HTTP, jwtCfg config.JWT, svc *usecase.WalletService, log *slog.Logger) (*Server, error) {
	if cfg.Mode == "" {
		gin.SetMode(gin.ReleaseMode)
	} else {
		gin.SetMode(cfg.Mode)
	}

	registerCustomValidators()

	// JWT validator runs before AuditContext so resolveActor() can prefer the
	// token subject over the X-Caller-Subject header. When jwtCfg.Enabled is
	// false the middleware is a no-op and the header fallback applies.
	jwtMW, err := middleware.JWT(middleware.JWTConfig{
		Enabled:      jwtCfg.Enabled,
		Issuer:       jwtCfg.Issuer,
		Audience:     jwtCfg.Audience,
		Algorithm:    jwtCfg.Algorithm,
		HMACSecret:   jwtCfg.HMACSecret,
		RSAPublicKey: jwtCfg.RSAPublicKey,
		RolesClaim:   jwtCfg.RolesClaim,
		ChannelClaim: jwtCfg.ChannelClaim,
		ClockSkew:    jwtCfg.ClockSkew,
	})
	if err != nil {
		return nil, err
	}

	r := gin.New()
	r.Use(
		gin.Logger(),                    // simple access log
		middleware.Recovery(),           // panic → 500 envelope
		middleware.RequestID(),
		middleware.FlowID(), // FlowId header/?flowId= → traceparent (before otelgin)
		otelgin.Middleware(cfg.ServiceName),
		middleware.AuditContext(),
	)
	if cfg.MetricsEnabled {
		// Record wallet_requests_total / wallet_request_duration_seconds for
		// every route. No-op when the global meter provider is the no-op one.
		r.Use(middleware.Metrics())
	}

	h := handler.New(svc)
	r.GET("/healthz", h.Healthz) // no request timeout, no JWT — cheap probe

	// Prometheus scrape endpoint (US-9.12). No JWT, no request timeout, no audit
	// — a cheap unauthenticated pull like /healthz, scraped on the pod network.
	// Serves the default Prometheus registry the OTel exporter registered into.
	if cfg.MetricsEnabled {
		r.GET("/metrics", gin.WrapH(promhttp.Handler()))
	}

	// Interactive API docs (OpenAPI/Swagger). Gated so prod can hide the API
	// surface (SWAGGER_ENABLED=false). Spec is generated by `make swagger`.
	if cfg.SwaggerEnabled {
		r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	// Transactional + treasury endpoints carry the hard ctx deadline (HLD §9)
	// and require a valid JWT when JWT_ENABLED=true.
	// Everything below this group inherits middleware.WithTimeout(cfg.RequestTimeout).
	v1 := r.Group("/v1")
	v1.Use(middleware.WithTimeout(cfg.RequestTimeout), jwtMW)
	{
		// ── Finance: money movement + ledger reads ──
		finance := v1.Group("/finance")
		{
			finance.POST("/topup", h.Topup)
			finance.POST("/transfer", h.Transfer)
			finance.POST("/withdraw", h.Withdraw)
			finance.POST("/merchant-deposit", h.MerchantDeposit)   // route deposit → settlement (cold) | shard (hot)
			finance.POST("/merchant-withdraw", h.MerchantWithdraw) // settlement withdraw + hot-shard sweep
			finance.POST("/fee-charge", h.FeeCharge)               // standalone fee + VAT charge (US-2.8)
			// Reversals are ops-only — RBAC gated by wallet.finance.reverse (US-9.10).
			reverse := finance.Group("", middleware.RequireAnyRole(middleware.RoleFinanceReverse))
			{
				reverse.POST("/merchant-withdraw/reverse", h.ReverseMerchantWithdraw) // credit-back principal + fee/VAT to settlement
				reverse.POST("/reverse", h.ReverseTransfer)                           // in-book transfer reversal (reference in body)
				reverse.POST("/topup/reverse", h.ReverseTopup)                        // topup reversal (reference in body)
				reverse.POST("/fee-charge/reverse", h.ReverseFeeCharge)               // reverse a standalone fee charge
			}
			finance.GET("/transactions", h.ListTransactions)         // account statement: ?acct_no=&limit=&before_seq=
			finance.GET("/transactions/:tran_key", h.GetTransaction) // all legs of one transaction
			finance.GET("/restraints", h.ListRestraints)             // list holds/liens: ?acct_no=&limit=&before_seq=
			finance.GET("/restraints/:id", h.GetRestraint)           // one restraint by id
			finance.POST("/restraints", h.AddRestraint)              // add a hold/lien
			finance.POST("/restraints/:id/release", h.ReleaseRestraint)
		}

		// ── Onboarding (OTP-free, US-1.1/1.7): client + KYC + first wallet in 1 TX ──
		v1.POST("/onboard", h.Onboard)

		// ── Clients: master CRUD + KYC update (US-1.2) ──
		clients := v1.Group("/clients")
		{
			clients.POST("", h.CreateClient)
			clients.GET("", h.ListClients)                              // MASKED list (?status=&client_type=&limit=&after=)
			clients.GET("/:client_no", h.GetClient)                     // MASKED profile (PII masked)
			clients.GET("/:client_no/accounts", h.ListAccountsByClient) // all wallets owned by the client
			clients.GET("/:client_no/360", h.GetClient360)              // MASKED 360 (profile + wallets + banks + restraints)
			clients.PATCH("/:client_no", h.UpdateClient)
			clients.POST("/:client_no/kyc", h.UpdateKYC)                              // submit/update eKYC + raise tier
			clients.POST("/:client_no/documents", h.AttachClientDocument)             // attach/update related document (US-1.13)
			clients.POST("/:client_no/banks", h.LinkClientBank)                       // link a bank account
			clients.PUT("/:client_no/banks/:link_id/default", h.SetDefaultClientBank) // set default bank
		}

		// ── Accounts: lifecycle (open / block / close) + profile + balance reads ──
		accounts := v1.Group("/accounts")
		{
			accounts.POST("", h.OpenAccount)                   // open wallet (count-limited)
			accounts.GET("/search", h.SearchAccounts)          // search by acct_no/client_no (q>=6) → masked name
			accounts.PATCH("/:acct_no", h.UpdateAccountStatus) // block / close / re-activate
			accounts.GET("/:acct_no", h.GetAccount)            // account profile (no client PII)
			accounts.GET("/:acct_no/balance", h.GetBalance)    // realtime + historical (?as_of_date=)
		}
		// ── Merchant groups: lifecycle (provision cold → activate → rescale) ──
		groups := v1.Group("/merchant-groups")
		{
			groups.POST("", h.ProvisionAcctGroup)                   // provision a cold group + settlement (US-1.10)
			groups.POST("/:group_id/activate", h.ActivateHotWallet) // promote cold group → 4|8|16 shards (US-1.9)
			groups.POST("/:group_id/rescale", h.RescaleHotWallet)   // grow hot tier 4→8→16 + rebalance (US-1.12)
		}
		// /v1/ops/* — privileged ops views. wallet.ops.read required (US-9.10).
		ops := v1.Group("/ops/accounts", middleware.RequireAnyRole(middleware.RoleOpsRead))
		{
			ops.GET("/search", h.SearchAccountsFull) // UNMASKED search (matches + returns raw client name)
			ops.GET("/:acct_no/balance", h.GetBalanceOps)
			ops.POST("/balance/batch", h.GetBalanceBatch)
		}
		opsClients := v1.Group("/ops/clients", middleware.RequireAnyRole(middleware.RoleOpsRead))
		{
			opsClients.GET("", h.ListClientsFull)                 // UNMASKED list (raw + decrypted phone/email)
			opsClients.GET("/:client_no", h.GetClientFull)        // UNMASKED profile (privileged, wallet_pii_ro)
			opsClients.GET("/:client_no/360", h.GetClientFull360) // UNMASKED 360 (raw + decrypted PII)
		}

		// ── Treasury: withdrawal disbursement state machine (S2S callbacks) ──
		// wallet.treasury role required (US-9.10) — only the Treasury Service S2S
		// identity should hit these.
		treasury := v1.Group("/treasury/withdrawals/:ext_payout_ref",
			middleware.RequireAnyRole(middleware.RoleTreasury))
		{
			treasury.POST("/acked", h.MarkAcked)
			treasury.POST("/disbursing", h.MarkDisbursing)
			treasury.POST("/completed", h.MarkCompleted)
			treasury.POST("/reverse", h.Reverse)
		}
	}

	srv := &http.Server{
		Addr:              cfg.Addr,
		Handler:           r,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       cfg.ReadTimeout,
		WriteTimeout:      cfg.WriteTimeout,
		IdleTimeout:       cfg.IdleTimeout,
	}
	return &Server{cfg: cfg, server: srv, log: log}, nil
}

// Start blocks until the server stops listening or the context is cancelled.
// Returns nil on graceful shutdown, error on listen failure.
func (s *Server) Start(ctx context.Context) error {
	errCh := make(chan error, 1)
	go func() {
		s.log.Info("HTTP server listening", slog.String("addr", s.cfg.Addr))
		if err := s.server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errCh <- err
			return
		}
		errCh <- nil
	}()

	select {
	case <-ctx.Done():
		shutdownCtx, cancel := context.WithTimeout(context.Background(), s.cfg.ShutdownTimeout)
		defer cancel()
		s.log.Info("HTTP server stopping")
		_ = s.server.Shutdown(shutdownCtx)
		return nil
	case err := <-errCh:
		return err
	}
}

// ----- custom validators ----------------------------------------------------

var (
	moneyRE  = regexp.MustCompile(`^\d{1,18}(\.\d{1,2})?$`)
	acctNoRE = regexp.MustCompile(`^[A-Z0-9]{8,20}$`)
)

func registerCustomValidators() {
	v, ok := binding.Validator.Engine().(*validator.Validate)
	if !ok {
		return
	}
	_ = v.RegisterValidation("money", validateMoney)
	_ = v.RegisterValidation("acct_no", validateAcctNo)
}

func validateMoney(fl validator.FieldLevel) bool {
	return moneyRE.MatchString(fl.Field().String())
}
func validateAcctNo(fl validator.FieldLevel) bool {
	return acctNoRE.MatchString(fl.Field().String())
}
