#!/usr/bin/env bash
# =============================================================================
# deploy/loadtest/k6.sh — run the k6 HTTP load test, then report how many
# WLT_TRAN_HIST ledger rows the run generated (grand total + by TRAN_TYPE).
#
# Usage:
#   bash deploy/loadtest/k6.sh                       # PEAK=100, BASE_URL=:8099 (k6 defaults)
#   bash deploy/loadtest/k6.sh -e PEAK=700           # forward ANY k6 -e flags through
#   BASE_URL=http://host:8099 bash deploy/loadtest/k6.sh -e PEAK=300
#
# How the count is attributed to THIS run: WLT_TRAN_HIST.SEQ_NO is a monotonic
# IDENTITY. We snapshot MAX(SEQ_NO) before the run; every row above that mark is
# attributable to this run — including each fee/VAT leg and reversal/sweep leg
# (one posting writes 2-5 history rows, so rows ≫ HTTP transactions).
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/../.."

CTN=wallet-postgres
PW="$(grep -E '^POSTGRES_PASSWORD=' .env | cut -d= -f2-)"
BASE="${BASE_URL:-http://localhost:8099}"
q() { docker exec -e PGPASSWORD="$PW" "$CTN" psql -U postgres -d wallet -tAc "$1"; }

s0="$(q "SELECT COALESCE(MAX(SEQ_NO),0) FROM WLT_TRAN_HIST;")"
echo "▶ WLT_TRAN_HIST high-water SEQ_NO before run: $s0"

# Don't let a threshold-breach exit code (k6 returns non-zero) skip the report —
# capture it and re-raise after the WLT_TRAN_HIST summary has printed.
k6_rc=0
k6 run -e BASE_URL="$BASE" "$@" deploy/loadtest/k6_wallet.js || k6_rc=$?

echo ""
echo "▶ WLT_TRAN_HIST rows generated by this run (SEQ_NO > $s0):"
docker exec -e PGPASSWORD="$PW" "$CTN" psql -U postgres -d wallet -c "
  SELECT COALESCE(TRAN_TYPE,'— TOTAL —') AS tran_type, count(*) AS rows
    FROM WLT_TRAN_HIST WHERE SEQ_NO > $s0
   GROUP BY ROLLUP(TRAN_TYPE)
   ORDER BY (TRAN_TYPE IS NULL), rows DESC;"

exit "$k6_rc"
